service_name: powerbi-refresh-status
stack: python
owner: *

app_deployment: false

cronjobs:
  - name: ref-***
    runtime: build
    schedule: "0 7,14,19 * * *"
    dockerfile: Dockerfile.cronjob.powerbi-ref
    args: "--company=***"
  - name: ref-*****
    runtime: build
    schedule: "0 7,14,19 * * *"
    dockerfile: Dockerfile.cronjob.powerbi-ref
    args: "--company=*****"

bigquery:   
  enabled: true

rbac:
  env:
    sit:
      users:
      - **
      groups:
      - ****

      
